module Samba::BearerLoginVerifier
  macro included
    include Shield::Verifier
    include Samba::AllClientIds

    def verify!(scope : Shield::BearerScope | String | Nil = nil)
      verify(scope).not_nil!
    end

    def verify(scope : Shield::BearerScope | String | Nil = nil)
      yield self, verify(scope)
    end

    def verify(scope : Shield::BearerScope | String | Nil = nil) : User?
      user? if verify?(scope)
    end

    # If token has no client ID, it is a user-generated bearer token, so it must
    # have been generated by the resource owner themselves.
    #
    # Otherwise, it was generated in an OAuth flow and must match this client's
    # ID
    def verify?(scope : Shield::BearerScope | String | Nil = nil) : Bool?
      return unless oauth_token?

      is_valid = oauth_token.active?
      scope.try { |_scope| is_valid &&= oauth_token.has_scope?(_scope.to_s) }

      oauth_token.client_id.try do |client_id|
        return is_valid && client_id.in?(all_client_ids)
      end

      is_valid
    end

    def user : User
      user?.not_nil!
    end

    getter? user : User? do
      oauth_token?.try &.sub.try { |sub| UserQuery.new.remote_id(sub).first? }
    end

    def oauth_token : OauthToken
      oauth_token?.not_nil!
    end

    getter? oauth_token : OauthToken? do
      raw_token?.try do |token|
        Samba.settings.verify_oauth_token.call(
          OauthToken.cache_key(token),
          ->{ OauthToken.verify(token) }
        )
      end
    end

    def raw_token : String
      raw_token?.not_nil!
    end
  end
end
